apiVersion: apps/v1
kind: Deployment
metadata:
  name: application
spec:
  replicas: 2
  selector:
    matchLabels:
      service: application
  template:
    metadata:
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "8080"
        prometheus.io/path: "/application/metrics"
      labels:
        service: application
        # killable: "true"
    spec:
      containers:
        - image: quarkus/application-jvm:1.0
          imagePullPolicy: Never
          name: application
          ports:
          - name: http
            containerPort: 8080
          # livenessProbe:
          #   httpGet:
          #     path: /application/health/live
          #     port: http
          #   failureThreshold: 2
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
          # readinessProbe:
          #   httpGet:
          #     path: /application/health/ready
          #     port: http
          #   failureThreshold: 2
          #   initialDelaySeconds: 3
          #   periodSeconds: 3
          # startupProbe:
          #   httpGet:
          #     path: /application/health
          #     port: http
          #   failureThreshold: 3
          #   periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: application
spec:
  type: NodePort
  ports:
  - port: 8080
  selector:
    service: application
