[tcp]

  [tcp.routers]
    [tcp.routers.application]
      entryPoints = ["http"]
      rule = "HostSNI(`*`)"
      service = "application-tcp"

  [tcp.services]
    [tcp.services.application-tcp.loadBalancer]
      [[tcp.services.application-tcp.loadBalancer.servers]]
        address = "application-1:8080"
      [[tcp.services.application-tcp.loadBalancer.servers]]
        address = "application-2:8080"