## Dynamic configuration
[http.services]
  [http.services.application.loadBalancer]
    [[http.services.application.loadBalancer.servers]]
      url = "http://application-1:8080/"
    [[http.services.application.loadBalancer.servers]]
      url = "http://application-2:8080/"
      
[http.routers]
  [http.routers.application]
    entryPoints = ["http"]
    rule = "PathPrefix(`/application`)"
    service = "application"