[http.services]
  [http.services.application.loadBalancer]
   [http.services.application.loadBalancer.healthCheck]
     path = "/application/health/ready"
    #  path = "/application/health/live"
     interval = "5s"
     timeout = "2s"
    [[http.services.application.loadBalancer.servers]]
      url = "http://application-1:8080/"
    [[http.services.application.loadBalancer.servers]]
      url = "http://application-2:8080/"
      
[http.routers]
  [http.routers.application]
    entryPoints = ["http"]
    rule = "PathPrefix(`/application`)"
    service = "application"

[tcp.services]
  [tcp.services.application.loadBalancer]
    [[tcp.services.application.loadBalancer.servers]]
      address = "application-1:8080"
    [[tcp.services.application.loadBalancer.servers]]
      address = "application-2:8080"

[tcp.routers]
  [tcp.routers.application]
    entryPoints = ["tcp"]
    # By default, routers listen to every entrypoints
    rule = "HostSNI(`*`)"
    service = "application"
